name: ci
on:
  workflow_call:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Test
        run: task test:all
        timeout-minutes: 4


  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m --verbose
